<!-- Subscribe to newsletter  http://www.jacklmoore.com/colorbox/ -->

<?php $popupNewsletter  =  Mage::getSingleton('core/session')->getPopupNewsletter(); ?>
<?php if(!$popupNewsletter && Mage::getStoreConfig('newsletterbox/newsletterbox_group/newsletterbox_onoff') == true): ?>

<div style="display:none">
    <div class='inline_content' style='padding:10px; background:#fff;'>
		<div id="newsletter-colorbox" class="" style="z-index: 9999999999999;" role="alert">
			<div class="newsletter-colorbox-container">
	  			<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/box/signup.phtml')->toHtml();?>
			</div>
		</div>
	</div>
</div>

<script type="text/javascript">
jQuery( document ).ready(function( $ ) {
	$.colorbox({
		inline:true,
		href:".inline_content"
    });
});
</script>

<?php //Mage::getSingleton('core/session')->setPopupNewsletter('true'); ?>
<?php endif; ?>
