<!-- Subscribe to newsletter  http://www.jacklmoore.com/colorbox/ -->

<?php $popupNewsletter  =  Mage::getSingleton('core/session')->getPopupNewsletter(); ?>
<?php if(!$popupNewsletter && Mage::getStoreConfig('newsletterbox/newsletterbox_includes/newsletterbox_onoff') == true): ?>

<div style="display:none">
    <div class='inline_content' style='padding:10px; background:#fff;'>
		<div id="newsletter-colorbox" class="" style="z-index: 9999999999999;" role="alert">
			<div class="newsletter-colorbox-container">
	  			<?php echo $this->getLayout()->createBlock('newsletter/subscribe')->setTemplate('newsletter/box/signup.phtml')->toHtml();?>
			</div>
		</div>
	</div>
</div>

<?php //Mage::getSingleton('core/session')->setPopupNewsletter('true'); ?>
<?php endif; ?>
