<div class="block block-subscribe">
    <div class="block-title">
      <strong><span><?php echo $this->__('Stay informed') ?></span></strong>
    </div>
    <div class="block-title">
      <h3><?php echo $this->__('Subscribe to the Newsletter') ?></h3>
      <p><?php echo $this->__('News and exciting offers directly to your email.') ?></p>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail" onsubmit="myfunc(event)">
        <div class="block-content">
            <div class="input-box">
               <input onfocus="this.value=''; this.removeClassName('blurred');" value="<?php echo $this->__('mail@yourmail.com') ?>" type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button id="newsletterboxSubmit" type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button" onclick="newsletterfunc(event)"><span><span><?php echo $this->__('Yes, please!') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
		$('newsletter').addClassName('blurred');
    //]]>

    jQuery( document ).ready(function( $ ) {

      function newsletterfunc(event)
      {
      	var newsletterSubscriberFormDetail = new VarienForm('newsletter-form');
        event.preventDefault();
      	var form_email = $('newsletter').getValue();
      	var params_form = $('newsletter-validate-detail');

        new Validation('newsletter');

      		new Ajax.Updater({ success: 'newsletter-form' }, '<?php echo $this->getUrl('newsletter/subscriber/new') ?>', {
      			asynchronous:true, evalScripts:false,
      			parameters: { email: form_email },
      			onComplete:function(request, json){Element.hide('newsletter-form'); Element.hide('news-loader'); Element.show('feedback');},
      			onLoading:function(request, json){Element.show('news-loader');},
      		});
          document.getElementById("newsletter-pop").className = "cd-display-none";
      }

    });
    </script>
</div>
