<div class="block block-subscribe">
    <div class="block-title">
      <strong><span><?php echo $this->__('Perfecting your taste palette') ?></span></strong>
    </div>
    <div class="block-title">
      <h3><?php echo $this->__('Subscribe to Invinitums Newsletter') ?></h3>
      <p><?php echo $this->__('Be inspired by our wines , recipes , news and exciting offers directly to your email.') ?></p>
    </div>
    <form action="<?php echo $this->getFormActionUrl() ?>" method="post" id="newsletter-validate-detail" onsubmit="myfunc(event)">
        <div class="block-content">
            <div class="input-box">
               <input onfocus="this.value=''; this.removeClassName('blurred');" value="<?php echo $this->__('mail@dinmail.se') ?>" type="text" name="email" id="newsletter" title="<?php echo $this->__('Sign up for our newsletter') ?>" class="input-text required-entry validate-email" />
            </div>
            <div class="actions">
                <button type="submit" title="<?php echo $this->__('Subscribe') ?>" class="button" onclick="myfunc(event)"><span><span><?php echo $this->__('Yes, please!') ?></span></span></button>
            </div>
        </div>
    </form>
    <script type="text/javascript">
    //<![CDATA[
        var newsletterSubscriberFormDetail = new VarienForm('newsletter-validate-detail');
		$('newsletter').addClassName('blurred');
    //]]>

    function myfunc(event)
    {
    	var newsletterSubscriberFormDetail = new VarienForm('newsletter-form');
        event.preventDefault();
    	var form_email = $('newsletter').getValue();
    	var params_form = $('newsletter-validate-detail');
    	//alert(params_form);
    	new Validation('newsletter');
    	if(echeck(form_email))
    	{
    		//alert(form_email);
    		//alert(Form.serialize($('newsletter-validate-detail')));
    		new Ajax.Updater({ success: 'newsletter-form' }, '<?php echo $this->getUrl('newsletter/subscriber/new') ?>', {
    			asynchronous:true, evalScripts:false,
    			parameters: { email: form_email },
    			onComplete:function(request, json){Element.hide('newsletter-form'); Element.hide('news-loader'); Element.show('feedback');},
    			onLoading:function(request, json){Element.show('news-loader');},

    		});
        document.getElementById("newsletter-pop").className = "cd-display-none";
    	}
    	else
    	{
    		//alert(form_email);
    		return false;
    	}
    }

    function echeck(str) {

    	var at="@"
    	var dot="."
    	var lat=str.indexOf(at)
    	var lstr=str.length
    	var ldot=str.indexOf(dot)
    	if (str.indexOf(at)==-1){
    		//alert("Invalid E-mail ID")
    		goProcedural()
    		return false
    	}

    	if (str.indexOf(at)==-1 || str.indexOf(at)==0 || str.indexOf(at)==lstr){
    		//alert("Invalid E-mail ID")
    		goProcedural()
    		return false
    	}

    	if (str.indexOf(dot)==-1 || str.indexOf(dot)==0 || str.indexOf(dot)==lstr){
    		//alert("Invalid E-mail ID")
    		goProcedural()
    		return false
    	}

    	if (str.indexOf(at,(lat+1))!=-1){
    		//alert("Invalid E-mail ID")
    		goProcedural()
    		return false
    	}

    	if (str.substring(lat-1,lat)==dot || str.substring(lat+1,lat+2)==dot){
    		//alert("Invalid E-mail ID")
    		goProcedural()
    		return false
    	}

    	if (str.indexOf(dot,(lat+2))==-1){
    		//alert("Invalid E-mail ID")
    		goProcedural()
    		return false
    	}

    	if (str.indexOf(" ")!=-1){
    		//alert("Invalid E-mail ID")
    		goProcedural()
    		return false
    	}

    	return true
    }

    function goProcedural()
    {
    	Element.show('error-news-msg');
    	Element.hide.delay(5, 'error-news-msg');
    }

    </script>
</div>
